// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0t8Vs1PZFfTSEMUoWJX1rrXKUpyhknGU',
    appId: '1:936006119802:web:e21c121bb8e6f98e7066c3',
    messagingSenderId: '936006119802',
    projectId: 'bhumik-rathod',
    authDomain: 'bhumik-rathod.firebaseapp.com',
    storageBucket: 'bhumik-rathod.appspot.com',
    measurementId: 'G-RL12GHYM66',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1x6uW0fOWr-W3oe8HhQSY4usbM1DV2nA',
    appId: '1:936006119802:android:5699cfeaa3ba452f7066c3',
    messagingSenderId: '936006119802',
    projectId: 'bhumik-rathod',
    storageBucket: 'bhumik-rathod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhqk2Dq4_dgpGI_kq8-fsbQmrMcMlsNlQ',
    appId: '1:936006119802:ios:7b341536344fe9447066c3',
    messagingSenderId: '936006119802',
    projectId: 'bhumik-rathod',
    storageBucket: 'bhumik-rathod.appspot.com',
    iosBundleId: 'com.portfolio.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhqk2Dq4_dgpGI_kq8-fsbQmrMcMlsNlQ',
    appId: '1:936006119802:ios:7b341536344fe9447066c3',
    messagingSenderId: '936006119802',
    projectId: 'bhumik-rathod',
    storageBucket: 'bhumik-rathod.appspot.com',
    iosBundleId: 'com.portfolio.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0t8Vs1PZFfTSEMUoWJX1rrXKUpyhknGU',
    appId: '1:936006119802:web:4971eaec40f994b97066c3',
    messagingSenderId: '936006119802',
    projectId: 'bhumik-rathod',
    authDomain: 'bhumik-rathod.firebaseapp.com',
    storageBucket: 'bhumik-rathod.appspot.com',
    measurementId: 'G-SH93R3RLBH',
  );
}
