class CertificationsUtils {
  static const List<String> certificates = [
    // "assets/certifications/ACC-CTIT_PPT.jpg",
    // "assets/certifications/DataIsGood-2024.jpg",
    // "assets/certifications/Flipkart_Grid-5.jpg",
    "assets/certifications/GAH_2024.jpg",
    "assets/certifications/GL-Flutter_2024.jpg",
    // "assets/certifications/GoogleCloud_API.png",
    // "assets/certifications/GoogleCloud_DK.png",
    "assets/certifications/IICPC_2024.png",
    "assets/certifications/Legalgeek-PU.jpg",
    // "assets/certifications/LU-C_Prog.png",
    // "assets/certifications/LU-Chatbot.png",
    // "assets/certifications/LU-DSA.png",
    "assets/certifications/LU-Flutter.jpg",
    // "assets/certifications/LU-HTML_CSS.png",
    // "assets/certifications/LU-JAVA_Prog.png",
    // "assets/certifications/LU-JavaScript.png",
    // "assets/certifications/LU-PHP.png",
    // "assets/certifications/LU-PostmanAPI.png",
    // "assets/certifications/LU-PythonProg.png",
    // "assets/certifications/LU-ReactJS.png",
    // "assets/certifications/LU-SQL.png",
    // "assets/certifications/MDW-AIIS.jpg",
    // "assets/certifications/Nirma-Quiz.jpg",
    "assets/certifications/NU-LogicXampify.jpg",
    "assets/certifications/NU-Series_Crackers.jpg",
    "assets/certifications/SPEC-TechnoFest_2022.jpg",
    // "assets/certifications/TataCrucible_2023.jpg",
    // Add more certifications here
  ];

  static const List<String> titles = [
    // "Anand Commerce College - CTIT PPT Competetion",
    // "Data is Good",
    // "Flipkart Grid 5.0",
    "Great AppSec Hackathon 2024",
    "Great Learning - Flutter 2024",
    // "Google Cloud - SKill Badge I",
    // "Google Cloud - SKill Badge II",
    "Inter IIT Collegiate Programming Contest 2024",
    "Legal Geek - Parul University Digital Hackathon",
    // "Let's Upgrade - C Programming",
    // "Let's Upgrade - Chatbot Development",
    // "Let's Upgrade - Data Structures and Algorithms",
    "Let's Upgrade - Flutter Development",
    // "Let's Upgrade - HTML and CSS",
    // "Let's Upgrade - Java Programming",
    // "Let's Upgrade - JavaScript",
    // "Let's Upgrade - PHP",
    // "Let's Upgrade - Postman API",
    // "Let's Upgrade - Python Programming",
    // "Let's Upgrade - ReactJS",
    // "Let's Upgrade - SQL",
    // "Anand Institute of Information Science - Modern Data Warehousing",
    // "Nirma University - Women Development Cell Quiz",
    "Nirma University - LogicXampify",
    "Nirma University - Beyond Coders Series Crackers",
    "Sardar Patel Education Campus - TechnoFest 2022",
    // "Tata Crucible 2023",
    // Add more titles here
  ];
}
